version: '3.4'

services:

  database:
    image: postgres:12.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auto

  redis:
    image: redis:6.0.1
    ports:
      - "6379:6379"
    restart: always
